import { createContext, useContext, useEffect, useMemo } from 'react'
import useContacts from '../features/contacts/useContacts'
import { useAuth } from './AuthContext'

const ContactsContext = createContext(null)

export function ContactsProvider({ children }) {
  const { session } = useAuth()
  const sessionUserId = session?.user?.id

  const {
    contacts,
    contactsLoading,
    contactsMessage,
    editingContact,
    contactForm,
    contactSaveLoading,
    contactSaveMessage,
    ocrError,
    contactCardFile,
    contactCardPreview,
    contactCardEnhancedFile,
    contactCardEnhancedPreview,
    contactCardRotation,
    contactCardEnhancing,
    businessCardScanning,
    businessCardOcrResult,
    duplicateCheckResult,
    duplicateDialogOpen,
    contactSearch,
    contactViewMode,
    selectedContact,
    selectedContactCardView,
    selectedCardUrl,
    selectedCardHasEnhanced,
    selectedCardHasOriginal,
    contactFormCardView,
    contactTypeLabels,
    filteredContacts,
    setContacts,
    setContactsMessage,
    setContactsLoading,
    setEditingContact,
    setContactForm,
    setContactSaveLoading,
    setContactSaveMessage,
    setOcrError,
    setContactCardFile,
    setContactCardPreview,
    setContactCardEnhancedFile,
    setContactCardEnhancedPreview,
    setContactCardRotation,
    setContactCardEnhancing,
    setBusinessCardScanning,
    setBusinessCardOcrResult,
    setDuplicateCheckResult,
    setDuplicateDialogOpen,
    setContactSearch,
    setContactViewMode,
    setSelectedContact,
    setSelectedContactCardView,
    setContactFormCardView,
    fetchContacts,
    openContactModal,
    closeContactModal,
    handleContactInput,
    deleteContact,
    saveContact,
    openContactDetail,
    getContactCardUrl,
    contactScanApi,
  } = useContacts({ sessionUserId })

  // Contacts laden wenn Session vorhanden
  useEffect(() => {
    if (session) {
      fetchContacts()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [session])

  const value = useMemo(() => ({
    contacts,
    contactsLoading,
    contactsMessage,
    editingContact,
    contactForm,
    contactSaveLoading,
    contactSaveMessage,
    ocrError,
    contactCardFile,
    contactCardPreview,
    contactCardEnhancedFile,
    contactCardEnhancedPreview,
    contactCardRotation,
    contactCardEnhancing,
    businessCardScanning,
    businessCardOcrResult,
    duplicateCheckResult,
    duplicateDialogOpen,
    contactSearch,
    contactViewMode,
    selectedContact,
    selectedContactCardView,
    selectedCardUrl,
    selectedCardHasEnhanced,
    selectedCardHasOriginal,
    contactFormCardView,
    contactTypeLabels,
    filteredContacts,
    setContacts,
    setContactsMessage,
    setContactsLoading,
    setEditingContact,
    setContactForm,
    setContactSaveLoading,
    setContactSaveMessage,
    setOcrError,
    setContactCardFile,
    setContactCardPreview,
    setContactCardEnhancedFile,
    setContactCardEnhancedPreview,
    setContactCardRotation,
    setContactCardEnhancing,
    setBusinessCardScanning,
    setBusinessCardOcrResult,
    setDuplicateCheckResult,
    setDuplicateDialogOpen,
    setContactSearch,
    setContactViewMode,
    setSelectedContact,
    setSelectedContactCardView,
    setContactFormCardView,
    fetchContacts,
    openContactModal,
    closeContactModal,
    handleContactInput,
    deleteContact,
    saveContact,
    openContactDetail,
    getContactCardUrl,
    contactScanApi,
  }), [
    contacts,
    contactsLoading,
    contactsMessage,
    editingContact,
    contactForm,
    contactSaveLoading,
    contactSaveMessage,
    ocrError,
    contactCardFile,
    contactCardPreview,
    contactCardEnhancedFile,
    contactCardEnhancedPreview,
    contactCardRotation,
    contactCardEnhancing,
    businessCardScanning,
    businessCardOcrResult,
    duplicateCheckResult,
    duplicateDialogOpen,
    contactSearch,
    contactViewMode,
    selectedContact,
    selectedContactCardView,
    selectedCardUrl,
    selectedCardHasEnhanced,
    selectedCardHasOriginal,
    contactFormCardView,
    contactTypeLabels,
    filteredContacts,
    setContacts,
    setContactsMessage,
    setContactsLoading,
    setEditingContact,
    setContactForm,
    setContactSaveLoading,
    setContactSaveMessage,
    setOcrError,
    setContactCardFile,
    setContactCardPreview,
    setContactCardEnhancedFile,
    setContactCardEnhancedPreview,
    setContactCardRotation,
    setContactCardEnhancing,
    setBusinessCardScanning,
    setBusinessCardOcrResult,
    setDuplicateCheckResult,
    setDuplicateDialogOpen,
    setContactSearch,
    setContactViewMode,
    setSelectedContact,
    setSelectedContactCardView,
    setContactFormCardView,
    fetchContacts,
    openContactModal,
    closeContactModal,
    handleContactInput,
    deleteContact,
    saveContact,
    openContactDetail,
    getContactCardUrl,
    contactScanApi,
  ])

  return (
    <ContactsContext.Provider value={value}>
      {children}
    </ContactsContext.Provider>
  )
}

export function useContactsContext() {
  const context = useContext(ContactsContext)
  if (!context) {
    throw new Error('useContactsContext must be used within ContactsProvider')
  }
  return context
}
